=== Draco-lang/Compiler/src/Draco.SourceGeneration/Lsp/LspModel.xsd
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://draco-lang.com/language-server-protocol/model"
  xmlns="http://draco-lang.com/language-server-protocol/model"
  attributeFormDefault="unqualified"
  elementFormDefault="qualified">

  <xs:element name="LspModel" type="LspModelType" />

  <xs:complexType name="LspModelType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="BuiltinType" type="BuiltinTypeType" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="BuiltinTypeType">
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="FullName" type="xs:string" use="required" />
  </xs:complexType>

</xs:schema>

=== Draco-lang/Compiler/src/Draco.Lsp/Model/LspModel.xml
<?xml version="1.0" encoding="utf-8" ?>
<LspModel
  xmlns="http://draco-lang.com/language-server-protocol/model"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://draco-lang.com/language-server-protocol/model ../../Draco.SourceGeneration/Lsp/LspModel.xsd">

  <BuiltinType Name="boolean" FullName="System.Boolean" />
  <BuiltinType Name="string" FullName="System.String" />
  <BuiltinType Name="integer" FullName="System.Int32" />
  <BuiltinType Name="uinteger" FullName="System.UInt32" />
  <BuiltinType Name="LSPAny" FullName="Newtonsoft.Json.Linq.JToken" />
  <BuiltinType Name="unknown" FullName="Newtonsoft.Json.Linq.JToken" />
  <BuiltinType Name="DocumentUri" FullName="Draco.Lsp.Model.DocumentUri" />

</LspModel>
